format on next load: false
logging:
  level: 1
  format: HH:mm:ss
opengl:
  debug: true
display:
  fullscreen: false
  size:
    width: 3200
    height: 1800
font:
  list:
  - Courier-New
  size: 1024
language: ENG_UK
pre-load:
  pys: []
  gpu:
    gen patch: []
    load patch:
    - box