format on next load: false
logging:
  level: 1
  format: HH:mm:ss
opengl:
  debug: true
display:
  fullscreen: false
  size:
    width: 1600
    height: 900
font:
  list:
  - Courier-New
  size: 1024
