format on next load: false
debug:
  toggle physics display: F4
  toggle debug display: F3
  toggle patches: F5
  patches:
    toggle: F5
    next layer: ADD
    previous layer: SUBTRACT
graphics:
  vsync: V
global:
  toggle freecam: F2
  exit: ESCAPE
  free mouse: F
free camera:
  up: SPACE
  down: LSHIFT
  forward: W
  backward: S
  left: A
  right: D
  slow: LMENU
  stop: X
player:
  forward: W
  backward: S
  left: A
  right: D
  crouch: LSHIFT
  jump: SPACE
