format on next load: false
credits:
  title: CREDITS
  attrib: James Brown - Everything
title:
  loading: Loading...
top:
  exit: Exit
  credits: Show Credits
game:
  name: ABSTRACT
server:
  port: 'Port:    '
  address: 'Address: '
  config: 'Config:  '
  open connection: Open Connection
  join: Join
  host: Host
  join title: Join Server
  host title: Host Server
module:
  heatsink:
    coolant rate:
      name: Coolant Rate
      desc: How quickly the module removes heat
    desc: Decreaces your heat level after 5 seconds of not increacing. Stacking this module decreaces the wait time and increaces the cooling rate.
spawn:
  spawning: Spawning...
  spawning in: Spawning in %.1fs
