format on next load: false
logging:
  level: 0
  format: HH:mm:ss
display:
  size:
    width: 800
    height: 600
  fullscreen: false
font:
  list:
  - Courier-New
  - Fixedsys
  size: 512
icon:
  list:
  - Settings
  size: 128