format on next load: false
game:
  vsync: V
  exit: ESCAPE
  free mouse: F
debug:
  toggle debug display: F3
  toggle physics display: F4
free camera:
  up: SPACE
  down: LSHIFT
  forward: W
  backward: S
  left: A
  right: D
  slow: LMENU
  stop: X
